<center>
    <img src="https://weclouddata.s3.amazonaws.com/images/logos/wcd_logo_new_2.png" width='30%'> 
</center>

----------

<h1 align="center"> Hackerrank Challenge </h1>
<br>
<center align="left"> <font size='4'>  Developed by: </font><font size='4' color='#33AAFBD'>WeCloudData</font></center>
<br>

----------

### Other option:
#### Leetcode
#### Codewar

## 1. Write a function

https://www.hackerrank.com/challenges/write-a-function/problem

In [ ]:
def is_leap(year):
    if year % 400 == 0:
        return True
    if year % 100 == 0:
        return False
    if year % 4 == 0:
        return True
    return False

year = int(input())
print(is_leap(year))

In [ ]:
def is_leap(year):
    return (year % 400 == 0) or (( year % 100 != 0) and (year % 4 == 0))

year = int(input())
print(is_leap(year))

## 2. Words Score

https://www.hackerrank.com/challenges/words-score/problem

In [9]:
output

[[0, 0, 0], [1, 1, 1], [2, 2, 2]]

In [3]:
x=3
x_values = [a for a in range(x+1)]

In [4]:
x_values

[0, 1, 2, 3]

In [ ]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            # Change this to `score += 1`
            ++score
    return score


n = int(input())
words = input().split()
print(score_words(words))

In [ ]:
def score_words(words):
    return sum(sum(char in 'aeiouy' for char in word) % 2 or 2 for word in words)

## 3. Company Logo

https://www.hackerrank.com/challenges/most-commons/problem

In [ ]:
from collections import Counter

def solution(logo):
  counter = Counter(sorted(logo)).most_common(3)
  for (alpha, count) in counter:
    print(alpha, count)

In [ ]:
Counter('google').most_common(3)

In [34]:
    x = 2
    y = 2
    z = 2
    n = 3
    i = range(x+1)
    j = range(y+1)
    k = range(z+1)
    output = [[a,b,c] for a in i for b in j for c in k if a+b+c!=n]
    output

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 1],
 [0, 2, 0],
 [0, 2, 2],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 2],
 [1, 2, 1],
 [1, 2, 2],
 [2, 0, 0],
 [2, 0, 2],
 [2, 1, 1],
 [2, 1, 2],
 [2, 2, 0],
 [2, 2, 1],
 [2, 2, 2]]

In [85]:
import numpy as np
n=8
m=4
array = np.arange(1,n+1)
A = np.arange(1,m)
B = np.arange(9,12)

In [86]:
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
A

array([1, 2, 3])

In [88]:
B

array([ 9, 10, 11])

In [91]:
# [sum() x==1 if i in A x ==-1 elif i in B for i in array]

In [90]:
score = 0
for i in array:
    if i in A:
        score+=1
    elif i in B:
        score-=1
score

3

In [7]:
students = []
for _ in range(5):
    name = str(input())
    score = float(input())
    students.append([name,score])

a
95
x
35
y
25
c
35
j
65


In [8]:
students

[['a', 95.0], ['x', 35.0], ['y', 25.0], ['c', 35.0], ['j', 65.0]]

In [9]:
x = sorted(students, key=lambda x: x[1])

In [13]:
y = sorted(students, key=lambda x: x[0])

In [14]:
x[1][1]

35.0

In [16]:
for s in students:
    if s[1] == sorted(students, key=lambda x: y[1])[1][1]:
        print(s[0])

x
c


In [ ]:
n, m = input().split()
lst = input().split()
A = set(input().split())
B = set(input().split())
print(sum([1 if i in A else -1 if i in B else 0 for i in lst]))

In [ ]:
if __name__ == '__main__':
    n=int(input())
    students = [[input(), float(input())] for _ in range(n)]
    second_low_mark = sorted(set([s[1] for s in students]))[1]
    for s, m in sorted(students):
        if m == second_low_mark:
            print(s)